import React, {useState} from "react";



const FlashCards = () => {

    const questionAnswer = [
        {question: 0, answer: "Welcome. Please shuffle."},
        {question: 1, answer: "Remove specifics and convert to ambiguities"},
        {question: 2, answer: "Think of the radio"},
        {question: 3, answer: "Don't be afraid of cliches"},
        {question: 4, answer: "Allow an easement (an easement is the abandonment of a stricture)"},
        {question: 5, answer: "What is the reality of the situation?"},
        {question: 6, answer: "Simple subtractions"},
        {question: 7, answer: "Are there sections? Consider transitions"},
        {question: 8, answer: "Turn it upside down"},
        {question: 9, answer: "Go slowly all around the outside"},
        {question: 10, answer: "A line has two sides"},
        {question: 11, answer: "Infinitesimal gradations"},
        {question: 12, answer: "Make an exhaustive list of everything you might do and do the last thing on the list"},
        {question: 13, answer: "Change instrument roles"},
        {question: 14, answer: "Into the impossible"},
        {question: 15, answer: "Accretion"},
        {question: 16, answer: "Ask people to work against their better judgment"},
        {question: 17, answer: "Disconnect from desire"},
        {question: 18, answer: "Take away the elements in order of apparent non-importance"},
        {question: 19, answer: "Emphasize repetitions"},
        {question: 20, answer: "Don't be afraid of things because they're easy to do"},
        {question: 21, answer: "Is there something missing?"},
        {question: 22, answer: "Don't be frightened to display your talents"},
        {question: 23, answer: "Use unqualified people"},
        {question: 24, answer: "Breathe more deeply"},
        {question: 25, answer: "How would you have done it?"},
        {question: 26, answer: "Honor thy error as a hidden intention"},
        {question: 27, answer: "Emphasize differences"},
        {question: 28, answer: "Only one element of each kind"},
        {question: 29, answer: "Do nothing for as long as possible"},
        {question: 30, answer: "Bridges: - build -burn"},
        {question: 31, answer: "Water"},
        {question: 32, answer: "You don't have to be ashamed of using your own ideas"},
        {question: 33, answer: "Make a sudden, destructive unpredictable action; incorporate"},
        {question: 34, answer: "Tidy up"},
        {question: 35, answer: "Consult other sources"},
        {question: 36, answer: "Do the words need changing?"},
        {question: 37, answer: "Use an unacceptable color"},
        {question: 38, answer: "Ask your body"},
        {question: 39, answer: "Humanize something free of error"},
        {question: 40, answer: "Use filters"},
        {question: 41, answer: "Balance the consistency principle with the inconsistency principle"},
        {question: 42, answer: "Fill every beat with something"},
        {question: 43, answer: "Discard an axiom"},
        {question: 44, answer: "Listen to the quiet voice"},
        {question: 45, answer: "What wouldn't you do?"},
        {question: 46, answer: "Is it finished?"},
        {question: 47, answer: "Decorate, decorate"},
        {question: 48, answer: "Put in earplugs"},
        {question: 50, answer: "Give the game away"},
        {question: 51, answer: "Reverse"},
        {question: 52, answer: "Abandon normal instruments"},
        {question: 53, answer: "Trust in the you of now"},
        {question: 54, answer: "Use fewer notes"},
        {question: 55, answer: "What would your closest friend do?"},
        {question: 56, answer: "Repetition is a form of change"},
        {question: 57, answer: "Distorting time"},
        {question: 58, answer: "Give way to your worst impulse"},
        {question: 59, answer: "Make a blank valuable by putting it in an exquisite frame"},
        {question: 60, answer: "The inconsistency principle"},
        {question: 61, answer: "Ghost echoes"},
        {question: 62, answer: "Don't break the silence"},
        {question: 63, answer: "You can only make one dot at a time"},
        {question: 64, answer: "Discover the recipes you are using and abandon them"},
        {question: 65, answer: "Just carry on"},
        {question: 66, answer: "Cascades"},
        {question: 67, answer: "(Organic) machinery"},
        {question: 68, answer: "Courage!"},
        {question: 69, answer: "What mistakes did you make last time?"},
        {question: 70, answer: "You are an engineer"},
        {question: 71, answer: "Consider different fading systems"},
        {question: 71, answer: "Mute and continue"},
        {question: 73, answer: "Look at the order in which you do things"},
        {question: 74, answer: "It is quite possible (after all)"},
        {question: 75, answer: "Go outside. Shut the door."},
        {question: 76, answer: "Don't stress one thing more than another"},
        {question: 77, answer: "Do we need holes?"},
        {question: 78, answer: "Cluster analysis"},
        {question: 79, answer: "Work at a different speed"},
        {question: 80, answer: "Do something boring"},
        {question: 81, answer: "Look closely at the most embarrassing details and amplify them"},
        {question: 82, answer: "Define an area as 'safe' and use it as an anchor"},
        {question: 83, answer: "Mechanicalize something idiosyncratic"},
        {question: 84, answer: "Overtly resist change"},
        {question: 85, answer: "Emphasize the flaws"},
        {question: 86, answer: "Accept advice"},
        {question: 87, answer: "Remember those quiet evenings"},
        {question: 88, answer: "Take a break"},
        {question: 89, answer: "The tape is now the music"},
        {question: 90, answer: "Short circuit (example: a man eating peas with the idea that they will improve his virility shovels them into his lap"},
        {question: 91, answer: "Imagine the music as a moving chain or caterpillar"},
        {question: 92, answer: "Use an old idea"},
        {question: 93, answer: "Intentions -credibility of, -nobility of, -humility of"},
        {question: 94, answer: "Destroy -nothing, -the most important thing"},
        {question: 95, answer: "Remember those quiet evenings"},
        {question: 96, answer: "Imagine the music as a set of disconnected events"},
        {question: 97, answer: "Change nothing and continue with immaculate consistency"},
        {question: 98, answer: "What are you really thinking about just now? Incorporate"},
        {question: 99, answer: "Children's voices -speaking -singing"},
        {question: 100, answer: "Assemble some of the instruments in a group and treat the group"},
        {question: 101, answer: "Feedback recordings into an acoustic situation"},
        {question: 102, answer: "Shut the door and listen from outside"},
        {question: 103, answer: "Towards the insignificant"},
        {question: 104, answer: "Is the tuning appropriate"},
        {question: 105, answer: "Simple a matter of work"},
        {question: 106, answer: "Look at a very small object, look at its center"},
        {question: 107, answer: "Not building a wall but making a brick"},
        {question: 108, answer: "Reevalution (a warm feeling)"},
        {question: 109, answer: "Disciplined self-indulgence"},
        {question: 110, answer: "The most important thing is the thing most easily forgotten"},
        {question: 111, answer: "Always first steps"},
        {question: 112, answer: "Idiot glee"},
        {question: 113, answer: "Question the heroic approach"},
        {question: 114, answer: "Be extravagant"},
        {question: 115, answer: "Always give yourself credit for having more than personality"},
        {question: 116, answer: "State the problem in words as clearly as possible"},
        {question: 117, answer: "Faced with a choice, do both"},
        {question: 118, answer: "Tape your mouth"},
        {question: 119, answer: "Twist the spine"},
        {question: 120, answer: "Get your neck massaged"},
        {question: 121, answer: "Lowest common denominator check: -single beat, -single note, -single riff"},
        {question: 122, answer: "Do the washing up"},
        {question: 123, answer: "Listen in total darkness, or in a very large room, very quietly"},
        {question: 124, answer: "Convert a melodic element into a rhythmic element"},
        {question: 125, answer: "Would anybody want it?"},
        {question: 126, answer: "Spectrum analysis"},
        {question: 127, answer: "Retrace your steps"},
        {question: 128, answer: "Go to an extreme, move back to a more comfortable place"},
        {question: 129, answer: "Once the search is in progress, something will be found"},
        {question: 130, answer: "Only a part, not the whole"},
        {question: 131, answer: "From nothing to more than nothing"},
        {question: 132, answer: "Be less critical more often"},
    ];
    
    const [randomNumber, setRandomNumber] = useState(0)
    
    const generateRandomNumber = () => {
        questionAnswer.shift();
        const randomNumber = Math.floor(Math.random() * questionAnswer.length);
        setRandomNumber(randomNumber)
    }

    return (
        <div className='ui container'>
            <h3>Oblique Strategies</h3>
            <div id='answer'>
                {questionAnswer[randomNumber].answer}
            </div>
            <div>
                <button className='ui-button' onClick={generateRandomNumber}>Shuffle</button>
            </div>
        </div>
    )
}

export default FlashCards;